[package]
name = "hidapi"
version = "0.4.1"
authors = [
    "Roland Ruckerbauer <roland.rucky@gmail.com>",
    "Osspial <osspial@gmail.com>",
    "Artyom Pavlov <newpavlov@gmail.com>"
]
repository = "https://github.com/Osspial/hidapi-rs"
description = "Rust-y wrapper around hidapi"
license = "MIT"
keywords = ["hid", "api", "usb","binding", "wrapper"]
build = "build.rs"
links = "hidapi"
documentation = "https://docs.rs/hidapi"

[features]
# Enable this feature to use hidraw backend instead of
# libusb-1.0 on Linux. Enabling this feature does not
# affect other platforms.
linux-hidraw = []

[dependencies]
libc = "0.2.15"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3.5"
